experiment_duration: 1000
preserve_population: true

selection:
  fitness_function: "fit"
  data: "./samples/2-MUX_overs-cohos-orbed_ALL.csv"
  d_fitness: 3
  t_size: 6
  fitness_sharing: true

genotype:
  max_depth: 8
  min_len: 4
  max_len: 500
  data_n: 7
  mutation_rate: 0.1

population:
  size: [20, 20]
  toroidal: true
  locality: 16
  n_elites: 10
  migration_rate: 0.1
  migration_type: "elite"

logging:
  log_every: 1
  save_every: 50
