experiment: "3-MUX-unweighted"
experiment_duration: 2000000
step_duration: 2
preserve_population: true

selection:
  fitness_function: "fit"
  data: "./samples/3-MUX_meaty-inane-flush_2048.csv"
  d_fitness: 3
  t_size: 6
  fitness_sharing: true
  trace: true
  lexical: true

genotype:
  max_depth: 8
  min_len: 4
  max_len: 400
  max_steps: 512
  output_reg: 1
  data_n: 11
  registers_n: 6 
  mutation_rate: 0.1
  weight_crossover_points: false

population:
  size: [12, 12]
  toroidal: true
  locality: 16
  n_elites: 10
  migration_rate: 0.5
  migration_type: "elite"

logging:
  log_every: 1
  save_every: 50
