experiment_duration: 50000
step_duration: 1
preserve_population: true
experiment: "2MUX-with-sharing-unweighted"

selection:
  fitness_function: "fit"
  data: "./samples/2-MUX_overs-cohos-orbed_ALL.csv"
  d_fitness: 3
  t_size: 6
  fitness_sharing: true
  trace: true
  lexical: true

genotype:
  max_depth: 8
  min_len: 4
  max_len: 200
  data_n: 6
  registers_n: 5
  output_reg: 1
  max_steps: 512
  mutation_rate: 0.1
  weight_crossover_points: false
  ops: "| & ~ mov"

population:
  size: [10, 10]
  toroidal: true
  locality: 16
  n_elites: 10
  migration_rate: 0.2
  migration_type: "elite"

logging:
  log_every: 1
  save_every: 50

dashboard:
  server: "0.0.0.0"
  port: 9124
  enable: true
