name = "Refusr"
uuid = "b1fc0893-9ae6-4706-afdc-455f54dfeac5"
authors = ["lucca <lucca.fraser@gmail.com>"]
version = "0.1.0"

[deps]
AbstractLattices = "398f06c4-4d28-53ec-89ca-5b2656b7603d"
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
AxisArrays = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
BenchmarkPlots = "ab8c0f59-4072-4e0d-8f91-a91e1495eb26"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Blink = "ad839575-38b3-5650-b840-f874b8c74a25"
Blosc = "a74b3585-a348-5f62-a45c-50e91977d574"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
Cockatrice = "9717ed07-727c-442c-8f6f-35ef42c1d4d5"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
Dash = "1b08a953-4be3-4667-9a23-3db579824955"
DashCoreComponents = "1b08a953-4be3-4667-9a23-9da06441d987"
DashDaq = "1b08a953-4be3-4667-9a23-a540cca008f6"
DashHtmlComponents = "1b08a953-4be3-4667-9a23-24100242a84a"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
DistributedArrays = "aaf54ef3-cdf8-58ed-94cc-d582ad619b94"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DrawSimpleGraphs = "1d51b185-1a84-59cf-b84e-03b0e3da30b7"
Espresso = "6912e4f1-e036-58b0-9138-08d1e6358ea9"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FunctionWrappers = "069b7b12-0de2-55c6-9aab-29f3d0a68a2e"
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
GZip = "92fee26a-97fe-5a0c-ad85-20a5f3185b63"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"
GraphRecipes = "bd48cda9-67a9-57be-86fa-5b3c104eda73"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
ImageInTerminal = "d8c32880-2388-543b-8c61-d9f865259254"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
ImageTransformations = "02fcd773-0e25-5acc-982a-7f6622650795"
ImageView = "86fae568-95e7-573e-a6b2-d8a6b900c9ef"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
InformationMeasures = "96684042-fbdc-5399-9b8e-d34e539a126c"
IntegerSequences = "b4b868b0-69a7-11e9-2db0-173b4e8e576c"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
MD5 = "6ac74813-4b46-53a4-afec-0b5dc9d7885c"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
MosaicViews = "e94cdb99-869f-56ef-bcf0-1ae2bcbe0389"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
PGFPlotsX = "8314cec4-20b6-5062-9cdb-752b83310925"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Plotly = "58dd65bb-95f3-509e-9936-c39a10fdeae7"
PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PrettyPrint = "8162dcfd-2161-5ef2-ae6c-7681170c5f98"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
RandomNumbers = "e6cf234a-135c-5ec9-84dd-332b85af5143"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
SimpleGraphs = "55797a34-41de-5266-9ec1-32ac4eb504d3"
SimplePosets = "b2aef97b-4721-5af9-b440-0bad754dc5ba"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
SymPy = "24249f21-da20-56a4-8eb1-6a02cf4ae2e6"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TikzPictures = "37f6aa50-8035-52d0-81c2-5a1d08754b2d"
TreeView = "39424ebd-4cf3-5550-a685-96706a953f40"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
Z3 = "06b161dc-0161-11ea-0f74-41f836f4024b"
