experiment_duration: 5000000
step_duration: 1
preserve_population: true
experiment: "23-bit-even-parity-no-xor"

selection:
  fitness_function: "fit"
  data: "./samples/23-bit-even-parity.csv"
  d_fitness: 4
  t_size: 6
  fitness_sharing: true
  trace: true
  lexical: false
  fitness_weights:
    dirichlet: 1000
    ingenuity: 300
    information: 200
    parsimony: 0


genotype:
  max_depth: 8
  min_len: 4
  max_len: 1024
  data_n: 11
  registers_n: 8
  output_reg: 1
  max_steps: 1024
  mutation_rate: 0.1
  weight_crossover_points: true
  ops: "nor nand | & ~ mov"

population:
  size: [15, 15]
  toroidal: true
  locality: 16
  n_elites: 10
  migration_rate: 1.0
  migration_type: "elite"

logging:
  log_every: 1
  save_every: 50

dashboard:
  server: "0.0.0.0"
  port: 9124
  enable: true
